# (Bildunterschrift, Suchbegriffe (Alternativen mit |), Pflicht-Stichworte im Dateinamen (Alternativen mit |))
IMGS=[
[("Supertrees","","","Singapore (SG), Gardens by the Bay, Supertree Grove -- 2019 -- 4752.jpg"),
 ("Marina Bay Sands","","","Marina Bay Sands and illuminated polyhedral building Louis Vuitton over the water at blue hour with pink clouds in Singapore.jpg"),
 ("Cloud Forest","","","Cloud Forest, Gardens by the Bay, Singapore.jpg"),
 ("Merlion","","","Merlión, Marina Bay, Singapur, 2023-08-18, DD 45-47 HDR.jpg"),
 ("Chinatown","","","Pagoda Street Chinatown Singapore.jpg"),
 ("Sentosa","Siloso Beach Sentosa|Sentosa island beach","sentosa|siloso")],
[("Christ Church","Christ Church Malacca|Christ Church Melaka","christ church"),
 ("Melaka-Fluss","Malacca River riverside|Melaka River","malacca river|melaka river"),
 ("Stadthuys","Stadthuys Malacca|Stadthuys Melaka","stadthuys"),
 ("A Famosa","A Famosa Porta de Santiago Malacca|A Famosa Malacca","famosa|santiago"),
 ("Straits Mosque","Malacca Straits Mosque|Masjid Selat Melaka","straits mosque|masjid selat"),
 ("Menara Taming Sari","Menara Taming Sari|Taming Sari Tower","taming sari")],
[("Petronas Towers","Petronas Twin Towers|Petronas Towers night","petronas"),
 ("Batu Caves","","","Batu Caves (18355395004).jpg"),
 ("Thean Hou Tempel","Thean Hou Temple Kuala Lumpur","thean hou"),
 ("Sultan Abdul Samad","Sultan Abdul Samad Building|Merdeka Square Kuala Lumpur","sultan abdul samad|merdeka"),
 ("Menara Kuala Lumpur","Menara Kuala Lumpur KL Tower|KL Tower","menara kuala lumpur|kl tower"),
 ("Jalan Alor","Jalan Alor food street|Jalan Alor","jalan alor")],
[("Perhentian Kecil","Perhentian Kecil beach|Pulau Perhentian Kecil","perhentian"),
 ("Perhentian Besar","Perhentian Besar beach|Pulau Perhentian Besar","perhentian"),
 ("Meeresschildkröte","green sea turtle Malaysia|Chelonia mydas swimming","turtle|chelonia"),
 ("Long Beach","Long Beach Perhentian Kecil|Perhentian Long Beach","perhentian"),
 ("Wassertaxi","Perhentian islands boat|Perhentian jetty","perhentian"),
 ("Korallenriff","Perhentian coral reef|Perhentian snorkeling","perhentian|coral")],
[("Wandkunst","George Town Penang street art mural|Penang street art","street art|mural"),
 ("Kek Lok Si","Kek Lok Si temple Penang|Kek Lok Si","kek lok si"),
 ("Chew Jetty","Chew Jetty Penang|Clan Jetties Penang","jetty|jetties"),
 ("Penang Hill","Penang Hill funicular|Penang Hill","penang hill|bukit bendera"),
 ("Khoo Kongsi","Khoo Kongsi Penang","khoo kongsi"),
 ("Blue Mansion","Cheong Fatt Tze Mansion|Blue Mansion Penang","cheong fatt tze|blue mansion")],
[("SkyBridge","Langkawi Sky Bridge","sky bridge|skybridge"),
 ("Cenang Strand","Pantai Cenang Langkawi|Cenang beach","cenang"),
 ("SkyCab","Langkawi Cable Car SkyCab|Langkawi cable car","cable car|skycab"),
 ("Mangroven Kilim","Kilim Karst Geoforest Park|Kilim Langkawi mangrove","kilim"),
 ("Tanjung Rhu","Tanjung Rhu Langkawi","tanjung rhu"),
 ("Telaga Tujuh","Telaga Tujuh waterfall Langkawi|Seven Wells waterfall","telaga tujuh|seven wells")],
[("Cheow-Lan-See","Cheow Lan Lake|Chiao Lan lake","cheow lan|chiew lan|chiao lan|cheow larn"),
 ("Kalksteinfelsen","Khao Sok National Park limestone|Khao Sok National Park","khao sok"),
 ("Ratchaprapha-Damm","Ratchaprapha Dam|Rajjaprabha Dam","ratchaprapha|rajjaprabha"),
 ("Regenwald","Khao Sok rainforest|Khao Sok jungle","khao sok"),
 ("Schwimmende Bungalows","Khao Sok floating raft house|Cheow Lan raft house","raft|floating"),
 ("Sok River","Khao Sok river|Sok River","sok")],
[("Rosa Delfine","Indo-Pacific humpback dolphin|Sousa chinensis","humpback|sousa"),
 ("Khanom","Khanom beach|Khanom district","khanom"),
 ("Küste bei Khanom","Khanom Nakhon Si Thammarat coast|Khanom","khanom"),
 ("Wat Phra Mahathat","Wat Phra Mahathat Woramahawihan Nakhon Si Thammarat","mahathat"),
 ("Longtailboot","long-tail boat Thailand beach|longtail boat Thailand","long-tail|longtail|long tail"),
 ("Kokospalmen","coconut plantation Nakhon Si Thammarat|coconut palms beach Thailand","coconut")],
[("Big Buddha","Big Buddha Koh Samui|Wat Phra Yai Ko Samui","big buddha|phra yai"),
 ("Wat Plai Laem","Wat Plai Laem Ko Samui|Wat Plai Laem","plai laem"),
 ("Lamai Beach","Lamai beach Ko Samui|Lamai Samui","lamai"),
 ("Chaweng Beach","Chaweng beach Ko Samui|Chaweng","chaweng"),
 ("Ang Thong","Ang Thong National Marine Park|Mu Ko Ang Thong","ang thong"),
 ("Na Muang Wasserfall","Na Muang waterfall Ko Samui|Namuang waterfall","muang")],
[("Koh Nang Yuan","Ko Nang Yuan sandbar|Koh Nang Yuan","nang yuan"),
 ("Sairee Beach","Sairee Beach Ko Tao|Sairee","sairee"),
 ("Koh Tao","Ko Tao island bay|Koh Tao","ko tao|koh tao"),
 ("Tanote Bay","Tanote Bay Ko Tao|Tanote Bay","tanote"),
 ("Shark Bay","Shark Bay Ko Tao|Thian Og bay","shark bay|thian og"),
 ("Mango Bay","Mango Bay Ko Tao|Ao Mamuang","mango bay|mamuang")],
[("Phraya-Nakhon-Höhle","Phraya Nakhon Cave Kuha Karuhas pavilion|Phraya Nakhon Cave","phraya nakhon|kuha karuhas"),
 ("Khao Sam Roi Yot","Khao Sam Roi Yot National Park|Sam Roi Yot","sam roi yot"),
 ("Bahnhof Hua Hin","Hua Hin railway station","hua hin"),
 ("Strand Hua Hin","Hua Hin beach|Hua Hin","hua hin"),
 ("Khao Takiab","Khao Takiab Hua Hin|Khao Takiap","takiab|takiap"),
 ("Laem Sala","Laem Sala beach Sam Roi Yot|Laem Sala","laem sala")],
[("Wat Arun","Wat Arun Bangkok|Wat Arun","wat arun"),
 ("Grand Palace","Grand Palace Bangkok Wat Phra Kaew|Wat Phra Kaew","grand palace|phra kaew"),
 ("Wat Pho","Wat Pho reclining Buddha|Wat Pho","wat pho|reclining"),
 ("Chinatown","Yaowarat Road Bangkok|Yaowarat","yaowarat|chinatown"),
 ("Ayutthaya","Wat Mahathat Ayutthaya Buddha head tree|Ayutthaya Historical Park","ayutthaya"),
 ("Chao Phraya","Chao Phraya River Bangkok boat|Chao Phraya Express boat","chao phraya")],
]
KEYS=['sg','melaka','kl','perh','penang','langkawi','khaosok','khanom','samui','tao','huahin','bkk']
_D=dict(zip(KEYS,IMGS))
_D['tioman']=[("Pulau Tioman","Tioman Island|Pulau Tioman","tioman"),
 ("Juara Strand","Juara beach Tioman|Pantai Juara","juara"),
 ("Salang","Salang Tioman|Kampung Salang","salang"),
 ("Tekek","Tekek Tioman|Kampung Tekek","tekek"),
 ("Dschungel","Tioman jungle|Tioman rainforest","tioman"),
 ("Korallenriff","Tioman coral reef|Tioman snorkeling","tioman")]
IMGS=[_D[k] for k in ['sg','tioman','kl','perh','penang','khanom','samui','tao','huahin','bkk']]
HERO=("Ko Nang Yuan|Koh Nang Yuan viewpoint","nang yuan")
